Attribute VB_Name = "ExprVisitor"
public function visitUnaryExpr(byval expression as UnaryExpr) as variant
end function


public function visitBinaryExpr(byval expression as UnaryExpr) as variant
end function


public function visitLiteralExpr(byval expression as UnaryExpr) as variant
end function


public function visitGroupingExpr(byval expression as UnaryExpr) as variant
end function


public function visitAssignExpr(byval expression as UnaryExpr) as variant
end function


public function visitVariableExpr(byval expression as UnaryExpr) as variant
end function


public function visitLogicalExpr(byval expression as UnaryExpr) as variant
end function


public function visitCallExpr(byval expression as UnaryExpr) as variant
end function


public function visitDotExpr(byval expression as UnaryExpr) as variant
end function


public function visitAccessorExpr(byval expression as UnaryExpr) as variant
end function


public function visitFunctExpr(byval expression as UnaryExpr) as variant
end function



