Attribute VB_Name = "StmtVisitor"
public function visitVarStmt(byval statement as VarStmt) as variant
end function


public function visitExprStmt(byval statement as ExprStmt) as variant
end function


public function visitPrintStmt(byval statement as PrintStmt) as variant
end function


public function visitBlockStmt(byval statement as BlockStmt) as variant
end function


public function visitIfStmt(byval statement as IfStmt) as variant
end function


public function visitWhileStmt(byval statement as WhileStmt) as variant
end function


public function visitFunctionStmt(byval statement as FunctionStmt) as variant
end function


public function visitClassStmt(byval statement as ClassStmt) as variant
end function


public function visitCodeStmt(byval statement as CodeStmt) as variant
end function


public function visitReturnStmt(byval statement as ReturnStmt) as variant
end function


public function visitForEachStmt(byval statement as ForEachStmt) as variant
end function


public function visitControlStmt(byval statement as ControlStmt) as variant
end function


public function visitEnumStmt(byval statement as EnumStmt) as variant
end function



